In [3]:
import numpy as np

In [4]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [3]:
a[1,2]

10

In [7]:
a[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [6]:
a[:, 2]

array([ 3, 10])

In [10]:
a[0, 1:-1]

array([2, 3, 4, 5, 6])

In [11]:
np.full((2,2), 78)

array([[78, 78],
       [78, 78]])

In [8]:
a[1,5] = 99
a[:,1] = [77,88]
print(a)

[[ 1 77  3  4  5  6  7]
 [ 8 88 10 11 12 99 14]]


In [12]:
b = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [13]:
b[1,0,0]

7

In [18]:
b[:,1,:] = [[99,88,88],[11,22,33]]
print(b)

[[[ 1  2  3]
  [99 88 88]]

 [[ 7  8  9]
  [11 22 33]]]


In [19]:
np.full([3,3], 77)

array([[77, 77, 77],
       [77, 77, 77],
       [77, 77, 77]])

In [20]:
np.full_like(a, 666)

array([[666, 666, 666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666, 666, 666]])

In [27]:
np.random.rand(3,3)

array([[0.49409927, 0.21379989, 0.74200006],
       [0.43429183, 0.50192029, 0.33686845],
       [0.55044636, 0.66543114, 0.98660934]])

In [68]:
np.random.randint(1,9,size = (3,3))

array([[5, 2, 1],
       [7, 2, 2],
       [3, 4, 8]])

In [70]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [80]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,5, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [81]:
aa = np.ones([5,5])
print(aa)

bb = np.zeros([3,3])
print(bb)

bb[1,1] = 9

aa[1:-1,1:-1] = bb
print(aa)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [84]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [88]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1)
print(h2)
np.hstack((h1,h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])